### ISSUE TITLE
resources等をできるだけ使い表現しよう

### ISSUE THREAD

**Issue by norotime** [KazuhiroObama/instagram_clone#10]
https://github.com/KazuhiroObama/instagram_clone/blob/865c173f112a9c46c81794a325c346d66b70ebeb/config/routes.rb#L6

@KazuhiroObama ルーティングは、resourcesやresourceでできるだけ記述して、onlyオプションで使わないものは制限するのが、王道です。

**Comment by norotime** [comment]
独自URLは、最終手段だと思っておきましょう。

**Comment by PEPSINEX** [comment]
了解です！

**Comment by PEPSINEX** [comment]
ルーティングと、それに伴う他ファイルを変更
