### ISSUE TITLE
自分のIDに紐づくものではないものを作成・削除できても良いのか再考しよう

### ISSUE THREAD

**Issue by norotime** [KazuhiroObama/instagram_clone#11]
https://github.com/KazuhiroObama/instagram_clone/blob/865c173f112a9c46c81794a325c346d66b70ebeb/app/controllers/icons_controller.rb#L15

**Comment by norotime** [comment]
@KazuhiroObama HTTPリクエストは、常に何がやってくるかわからない前提で実装をお願いします。

**Comment by PEPSINEX** [comment]
外部から呼び出せないように、privateメソッドに記述する。という認識でよろしいですか？

追記：すみません。不必要なcontrollerを残していました。icons_controller.rbを削除します。Issueの意味の捉え方の確認だけさせて下さい。

**Comment by norotime** [comment]
@KazuhiroObama HTMLを改ざんすれば、ID値は好き勝手に変えられますよね？
どのようなIDが飛んできたとしても、自分が投稿したものなど仕様通りに動くようにしましょう。

**Comment by norotime** [comment]
DAY01で体験した、Chrome>検証 でコードを編集できたことを思い出してください。

**Comment by PEPSINEX** [comment]
あー、了解です。理解しました。
検証モードを利用する事で、任意のキーや値を送信できるのでしたね。

今後はcontrollerで値を挿入するか、値が本当に正しいか確認するメソッドを使用していきます。
ありがとうござます。認識不足でした。

**Comment by norotime** [comment]
@KazuhiroObama そうです〜。常に暗闇の中でコントローラは、ドキドキしながら何がやってくるのかを待っていると思ってください。パラメータインザダークです。w
http://www.dialoginthedark.com/

**Comment by PEPSINEX** [comment]
@norotime 暗闇の中にいるのなら、適切な情報を与えてあげないといけませんね！面白そうなリンクもありがとうございます！！
