### ISSUE TITLE
使用しているGemのコメントアウトは削除しよう

### ISSUE THREAD

**Issue by norotime** [KazuhiroObama/instagram_clone#3]
https://github.com/KazuhiroObama/instagram_clone/blob/865c173f112a9c46c81794a325c346d66b70ebeb/Gemfile#L31

@KazuhiroObama デフォルトでコメントアウトしているものは、よく使うGemだからです。重複しているのは削除しましょう。

**Comment by PEPSINEX** [comment]
不要なコメントアウト削除しました
