### ISSUE TITLE
メソッド間は空行を入れて読みやすくしよう

### ISSUE THREAD

**Issue by norotime** [KazuhiroObama/instagram_clone#6]
https://github.com/KazuhiroObama/instagram_clone/blob/865c173f112a9c46c81794a325c346d66b70ebeb/app/helpers/application_helper.rb#L8

@KazuhiroObama 一度、スタイルガイドの見出しを全て読み込みましょう。https://github.com/fortissimo1997/ruby-style-guide/blob/japanese/README.ja.md

**Comment by PEPSINEX** [comment]
メソッド間に適切な空行の挿入。スタイルガイド準拠
