### ISSUE TITLE
配列のインデックスをベタで記述しているのが気になります

### ISSUE THREAD

**Issue by norotime** [KazuhiroObama/instagram_clone#7]
https://github.com/KazuhiroObama/instagram_clone/blob/865c173f112a9c46c81794a325c346d66b70ebeb/app/controllers/pictures_controller.rb#L75

@KazuhiroObama これは、どのような処理で使われていますか？

**Comment by PEPSINEX** [comment]
set_user_idメソッドは使用されていません。無駄な記述でした。

**Comment by norotime** [comment]
@KazuhiroObama なんとナントなんと・・・

**Comment by PEPSINEX** [comment]
データの取得方法の変更、不要な記述削除
