### ISSUE TITLE
トップページがログイン画面というのはいささか気になりました

### ISSUE THREAD

**Issue by norotime** [KazuhiroObama/instagram_clone#9]
https://github.com/KazuhiroObama/instagram_clone/blob/865c173f112a9c46c81794a325c346d66b70ebeb/config/routes.rb#L2

ログインしていなければリダイレクトが良いと思いましたがどうでしょう〜？

**Comment by PEPSINEX** [comment]
その方が無駄がなく良さそうですね！ありがとうございます。

**Comment by PEPSINEX** [comment]
root to を変更。
